# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndTest
  displayName: Build/Test
  jobs: 
  - job: buildTestJob
    displayName: Build and Test
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'

  - job: apiTest
    displayName: Postman API Tests
    steps:
    - task: DockerCompose@0
      env:
        DOCKER_BUILDKIT: 1
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.apitest.yml'
        qualifyImageNames: false
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'run apitest'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/newman-report.xml'
        testRunTitle: 'Postman API Tests'


