version: '3.7'

services:
  mldbapi:
    image: mldbapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - devdb
      - mock-oath2-server
    ports:
      - 5000:5000
    environment:
      - AUTHENTICATION__INSECUREMETADATA=true
      - AUTHENTICATION__DOMAIN=http://mock-oauth2-server:8080/testTokenIssuer
      - AUTHENTICATION__AUDIENCE=https://mldb
      - CONNECTIONSTRINGS__PGCONN=Host=devdb;Port=5432;Username=postgres;Password=password
  devdb:
    image: devdb
    build:
      context: .
      dockerfile: Dockerfile.devdb
    ports:
      - 5432:5432
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.8
    ports:
      - 8080:8080
    environment:
      JSON_CONFIG: |
        {
            "interactiveLogin": true,
            "httpServer": "NettyWrapper",
            "tokenCallbacks": [
                {
                    "issuerId": "testTokenIssuer",
                    "tokenExpiry": 600,
                    "requestMappings": [
                        {
                            "requestParam": "scope",
                            "match": "apitest",
                            "claims": {
                                "sub": "testUser",
                                "aud": [
                                    "https://mldb"
                                ],
                                "https://mldb/claims/name": "Testy McUserson"
                            }
                        }
                    ]
                }
            ]
        }
